Contributors guide
amadeus4dev/amadeus-android pull request #48
Opened 2021-01-12 21:05 UTC by pietrini

2021-01-13 17:07 UTC, anthonyroux requested changes

2021-01-14 20:06 UTC, pietrini commented on .github/CONTRIBUTING.md
> +To run the tests using a terminal use you can use gradle.
This command only runs Unit tests and avoid other integration tests as they can be flaky due to api responses.
There is no real way to do this using Android Studio as far as I know.
Should we keep it that way or you prefer I investigate a way to apply this filter on a custom Android Studio custom gradle task ?

2021-01-15 12:52 UTC, anthonyroux commented on .github/CONTRIBUTING.md
> +To run the tests using a terminal use you can use gradle.
Ok. No worries, then we can just mention it: ## Unit-tests in terminal .... // ## Unit-test and Integration tests in Android Studio ... with a note: note that integration tests are here for you to validate your code. We do not run Integration tests on the continuous integration process (only unit-tests).

2021-01-19 11:53 UTC, anthonyroux approved these changes

2021-01-19 11:53 UTC, merged